Removed used of deprecated forced_unwind
bloomberg/quantum pull request #158
Opened 2022-06-27 20:47 UTC by juanalday

*Issue number of the reported bug or feature request: #157*

**Describe your changes**
It replaces the (removed) used of boost::coroutine2::detail::forced_unwind in a catch with boost::context

**Testing performed**
Just a basic compilation.

**Additional context**
Details described in issue #157

2022-06-28 04:09 UTC, juanalday commented
To @safaruqi for review

2022-08-10 15:44 UTC, arosenzweig3 requested changes

2022-08-10 16:56 UTC, juanalday commented on quantum/util/impl/quantum_sequencer_experimental_impl.h
> +    catch(const boost::context::detail::forced_unwind&)
I believe the only reference in that file is in a comment: 
```
    //NOTE: 'boost::coroutines2::detail::forced_unwind' is deprecated
    using CoroutineStackUnwind = boost::context::detail::forced_unwind;
```

2022-08-10 16:58 UTC, arosenzweig3 commented on quantum/util/impl/quantum_sequencer_experimental_impl.h
> +    catch(const boost::context::detail::forced_unwind&)
Ah, apologies, I mis-read and believed the using directive was pointing to the deprecated exception.

2022-08-10 16:58 UTC, arosenzweig3 approved these changes
Looks good.

2024-05-31 07:42 UTC, closed without merging